### ISSUE TITLE
Mediapipe pose estimation performance 

### ISSUE THREAD

**Issue by lanzani** [opencv/opencv_zoo#220]
Hi! 
I'm opening this issue because I'm a bit confused...

I have OpenCV 4.8.0 built on Jetson Nano and the dnn module works great with some of the examples provided. 
But I when I run the python example of mediapipe pose estimation the frame rate is kinda slow (around ~7fps with a webcam) and it doesn't change much when I switch from CPU to GPU.

On this [PR](https://github.com/opencv/opencv_zoo/pull/152) I read: 
> The inference time is long because the fusion and winograd function is disabled, this is a bug has been fixed, need to wait for the next version released to achieve maximum performance.

And I've read that this bug has been solved with OpenCV 4.8.0, which I'm using. Is this correct? 

But then I've installed mediapipe GPU on my jetson nano thanks to a [wheel made by a member of the community](https://github.com/PINTO0309/mediapipe-bin). I executed a basic example of pose estimation, and it is quite fast: I was able to get ~20fps.

My questions are: what can cause the difference in the inference time? Can opencv dnn reach the same performance as mediapipe?

Also, thank you for your great work :)

**Comment by fengyuentau** [comment]
@WanliZhong Please take a look into this problem.

**Comment by WanliZhong** [comment]
Hi, @lanzani Thanks for your question. The part that takes the most time is person detection before pose estimation. In OpenCV Zoo, each frame will run person detection + pose estimation. Here's why OpenCV Zoo is slower than mediapipe:

1. Mediapipe use a tracking method to track the person (based on their model) between each frame. That's mean for most frames, it will only run estimation part. So in theory, Mediapipe will cost time only from pose estimation. But OpenCV Zoo will cost time from detection and estimation.
2. Demo in OpenCV Zoo will inference all outputs. You can disabled unnecessary  outputs like heatmap, 3D points in here. That's will reduce much inference time. https://github.com/opencv/opencv_zoo/blob/b6e370b10f641879a87890d44e42173077154a05/models/pose_estimation_mediapipe/mp_pose.py#L95
3. Before estimation, the person image will be padded in here. It will cost much time even the method in OpenCV is fast then numpy. But I think there should be another way to do this. https://github.com/opencv/opencv_zoo/blob/b6e370b10f641879a87890d44e42173077154a05/models/pose_estimation_mediapipe/mp_pose.py#L69
4. If you install opencv by `pip install`, you will not have access to GPU. If you run on CUDA, OpenCV will fallback to CPU to run this model. You should build opencv with python and CUDA manually. That's why you change the backend to CUDA but have no effect.

**Comment by lanzani** [comment]
Thank you very much for your reply!

1. That's interesting, I didn't know that.
2. I will try, thanks!
3. Have you got any hints on what could be a better approach?
4. Yes, I've built opencv from source with CUDA and CUDA_DNN, I'm using [this](https://hub.docker.com/layers/federicolanzani/opencv-cuda-jetson/l4t-base-r32.7.1-python3.10.11/images/sha256-ea08c915c3c71a4c940e7bb7cde7a7a419a5daa1fa09fafa871e3cf2eefd9906?context=explore) container made with [this](https://github.com/lanzani/opencv-cuda-jetson-docker/blob/main/ubuntu18.04-py3.10.11/build_python3.10.11/Dockerfile) Dockerfile, (and without the container the behaviour I describe below is the same) and I think it works for the following reasons: 
    - When I run Opencv zoo mediapipe **pose detection** with **-bt 0** I got around **10 fps** on jetson nano
    - When I run Opencv zoo mediapipe **pose detection** with **-bt 1** I got around **22 fps** on jetson nano
    But then:
    - When I run Opencv zoo mediapipe **pose estimation** with **-bt 0** I got around **7 fps** on jetson nano 
    - When I run Opencv zoo mediapipe **pose estimation** with **-bt 1** I got the same **7 fps** on jetson nano as I do with **-bt 0** 

Did you remember having the same behavior as mine, or I got something wrong?
Thank you very much :)

**Comment by WanliZhong** [comment]
@lanzani Hi, for 3. I think it's ok. It's not the most time cost part.  For 4. you can check the [benchmark result](https://raw.githubusercontent.com/opencv/opencv_zoo/main/benchmark/color_table.svg). As the test results, pose estimation on CUDA do slower than on CPU. It's because opencv's dnn module does not support cuda well

**Comment by lanzani** [comment]
Thank you for the clarifications :)
