### ISSUE TITLE
torch.nn.functional.interpolate is unsupport!

### ISSUE THREAD

**Issue by Wwupup** [opencv/opencv_zoo#81]
I meet error when run:
`python demo.py -m model.onnx -i imgfile.jpg`
![83f9eacadf6f2ef4705beb3d534d15f](https://user-images.githubusercontent.com/70632698/183413451-aa80214e-2a6b-46f5-906d-f7609b991f21.png)
It seems that the latest version don`t support upsample operation.
The onnx model in Netron:
![9cff13bbe00711cefe483c97a7237e8](https://user-images.githubusercontent.com/70632698/183413712-b6dc6dbb-b5fb-447b-adb4-e316bd555f2f.png)

**Comment by fengyuentau** [comment]
The problems are:
1. OpenCV DNN does not support ONNX model with dynamic input shape. However, we have a clear plan to support this in OpenCV 5.x.
2. For fixed input shape, the resize operators have fixed target size as input. So for OpenCV DNN, when it takes a input of different size, the ouputs of resize operators will have a wrong shape.

Current solution is:
1. Export this model with resize operators with scale 2 as input instead of fixed size.
2. Resize the input so that its width and height can be divisible by 64.
3. Get the lastest OpenCV: `pip install opencv-python-rolling`.

Code needs to be changed in [libfacedetection.train](https://github.com/ShiqiYu/libfacedetection.train/blob/a3bc97c7e85bb206c9feca97fbd541ce82cfa3a9/model/nets/yuhead.py#L51-L52):

```.diff
-                size=[feats[i].size(2), feats[i].size(3)], 
+                scale = 2,
```
