### ISSUE TITLE
onnx files fail to open

### ISSUE THREAD

**Issue by flamencoipython** [opencv/opencv_zoo#93]
why do onnx files provided by face_detection_yunet fail to open?

**Comment by fengyuentau** [comment]
I guess you need to install git-lfs to pull lfs objects (.onnx files).

**Comment by Vincen-31** [comment]
Actually, I have the similar error. 
1. I have already downloaded the .onnx files by downloading zip  and checked the path in demo.py.
2. I have  tried running code with absolute path of .onnx files.
3. I deploy the object_tracking_dasiamrpn with python 3.6 3.8 and opencv 4.5.4.58 4.6.0.66, but failed.
Hardware:
os : ubuntu 18.04 x64
when I run **python demo.py** , I get the follow error:

Traceback (most recent call last):
  File "demo.py", line 54, in <module>
    model = DaSiamRPN(
  File "/home/milab/Projects/PycharmProjects/pythonProject/opencv_zoo/models/object_tracking_dasiamrpn/dasiamrpn.py", line 24, in __init__
    self._model = cv.TrackerDaSiamRPN.create(self._param)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:260: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: object_tracking_dasiamrpn_model_2021nov.onnx in function 'ONNXImporter'
Please help me.

**Comment by fengyuentau** [comment]
@Vincen-31 Your issue, including the one from OP, is all because of the git LFS object not being pulled properly. If you do not install git-lfs when doing `git clone`, or directly download via the `Download ZIP` button, the models (git-lfs objects) will not be fetched properly. Typically speaking, a deep learning model is at least several megabytes (one exception in opencv zoo is face_detection_yunet, which is ~330KB), but you can observe that the not-properly-fetched models are always 131B. And if you open those non-properly-fetched models with your text editor, you can see something as follows:

```
 version https://git-lfs.github.com/spec/v1
 oid sha256:176794409ae5e9d44b268297b1c480ba7f6df9f793a81d22eac4520aaf331594
 size 119815
```


I can see there are two methods to download models properly:
- Install git-lfs as said in the front page readme and run `git clone https://github.com/opencv/opencv_zoo.git` to get the whole opencv zoo with all models.
- Click into the model you want to download and click the `download` button in the webpage. Example: https://github.com/opencv/opencv_zoo/blob/master/models/face_detection_yunet/face_detection_yunet_2022mar.onnx.

**Comment by Vincen-31** [comment]
@fengyuentau Thanks for your reply. I have fixed the problem by following your instrction.
